name: Deployments example

run-name: Pipeline run by @${{ github.actor }}

on:
  push:
    branches: ['main', 'develop']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/

  deploy-dev:
    needs: [build-and-test]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.DEV_VERSION }}
    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v3
        with:
          name: archive.zip

      - name: release to dev
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ vars.DEV_VERSION }}
          token: ${{secrets.DEV_TOKEN}}
          prerelease: true
          draft: true
          name: Development
          files: archive.tar.gz

  deploy-prod:
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.PROD_VERSION }}
    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v3
        with:
          name: archive.zip

      - name: release to main
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ vars.PROD_VERSION }}
          token: ${{secrets.PROD_TOKEN}}
          generate_release_notes: true
          name: Production
          files: archive.tar.gz
