name: create-repo-issue

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      title:
        description: 'Issue Title'
        required: true
        type: string
      body:
        description: 'Issue Body'
        required: true
        type: string

jobs:
  create_issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write
    steps:
      - name: Create Issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.token }}' \
          --header 'content-type: application/json' \
          --data '{ 
            "title": "Failure: ${{ inputs.title }}",
            "body": "Details: ${{ inputs.body }}" 
            }' \
          --fail
