name: Create demo issue

on:
  push:

permissions:
  issues: write

jobs:
  msg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simple demo for reusable workflow"

  issue:
    uses: rndrepos/common/.github/workflows/create-repo-issue.yml@main
    with:
      title: 'Test Issue'
      body: 'Test Body'
    secrets:
      token: ${{ secrets.PAT }}
