name: report

run-name: Pipeline run by @${{ github.actor }}

on:
  push:
    branches: ['main', 'develop']

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build-stage: ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}
    steps:
      - name: Set debug
        id: set-debug-stage
        run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.14.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      artifact-tag: ${{ steps.changelog.outputs.version }}

  report:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get stage
        run: echo "The build stage is ${{ needs.setup.outputs.build-stage }}"
