name: file tree

on:
  workflow_dispatch:

jobs:
  fie-tree:
    runs-on: self-hosted

    steps:
      - name: Install tree
        run: |
          brew update
          brew install tree
      - name: Execute tree
        run: time tree | tee filetreelist.text
